[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.0"

[dependencies]
borsh = "1.5.1"
clap = "2.33.3"
serde = "1.0.210"
serde_derive = "1.0.130"
serde_json = "1.0.128"
solana-account-decoder = "2.0.3"
solana-clap-utils = "2.0.3"
solana-cli-config = "2.0.3"
solana-cli-output = "2.0.3"
solana-client = "2.0.3"
solana-logger = "2.0.3"
solana-program = "2.0.3"
solana-remote-wallet = "2.0.3"
solana-sdk = "2.0.3"
spl-associated-token-account = { version = "=5.0.1", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-associated-token-account-client = { version = "=1.0.0", path = "../../associated-token-account/client" }
spl-stake-pool = { version = "=2.0.0", path = "../program", features = [
  "no-entrypoint",
] }
spl-token = { version = "=6.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
bs58 = "0.5.1"
bincode = "1.3.1"

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
